/** Cortes editoriais (frações 0–1 da página renderizada). Revisáveis no admin. */
export type DossierBlockViewport = "mobile" | "desktop";

export type EditorialCrop = {
  id: string;
  order: number;
  viewport: DossierBlockViewport;
  label?: string;
  yStart: number;
  yEnd: number;
  xStart?: number;
  xEnd?: number;
  altText: string;
  /** Não repetir título acessível quando já aparece no raster. */
  omitUiLabel?: boolean;
};

/** Mobile: colunas verticais legíveis (~390px), ordem de leitura. */
export const BANFIELD_MOBILE_CROPS: EditorialCrop[] = [
  {
    id: "m01-capa",
    order: 1,
    viewport: "mobile",
    label: "Capa e resumo do caso",
    yStart: 0,
    yEnd: 0.12,
    altText: "Capa do dossiê Família Banfield.",
    omitUiLabel: true,
  },
  {
    id: "m02-fotos-vitimas",
    order: 2,
    viewport: "mobile",
    label: "Vítimas",
    yStart: 0.12,
    yEnd: 0.304,
    xStart: 0,
    xEnd: 0.34,
    altText: "Fotos das vítimas Christine e Joseph Banfield.",
  },
  {
    id: "m03-resumo-texto",
    order: 3,
    viewport: "mobile",
    yStart: 0.12,
    yEnd: 0.304,
    xStart: 0.34,
    xEnd: 0.66,
    altText: "Resumo editorial do caso Banfield.",
    omitUiLabel: true,
  },
  {
    id: "m04-dados-caso",
    order: 4,
    viewport: "mobile",
    label: "Local e data",
    yStart: 0.12,
    yEnd: 0.304,
    xStart: 0.66,
    xEnd: 1,
    altText: "Vítimas, local Fairfax Virginia e data do crime.",
  },
  {
    id: "m05-mapa",
    order: 5,
    viewport: "mobile",
    label: "Mapa",
    yStart: 0.304,
    yEnd: 0.416,
    altText: "Mapa de Fairfax e região metropolitana de Washington.",
    omitUiLabel: true,
  },
  {
    id: "m05b-timeline-titulo",
    order: 6,
    viewport: "mobile",
    label: "Linha do tempo",
    yStart: 0.416,
    yEnd: 0.452,
    altText: "Título da seção linha do tempo.",
    omitUiLabel: true,
  },
  {
    id: "m06-timeline-1",
    order: 15,
    viewport: "mobile",
    label: "Linha do tempo — out. 2021",
    yStart: 0.452,
    yEnd: 0.605,
    xStart: 0,
    xEnd: 0.2,
    altText: "Linha do tempo: outubro de 2021.",
    omitUiLabel: true,
  },
  {
    id: "m07-timeline-2",
    order: 7,
    viewport: "mobile",
    label: "Linha do tempo — ago. 2022",
    yStart: 0.452,
    yEnd: 0.605,
    xStart: 0.2,
    xEnd: 0.4,
    altText: "Linha do tempo: agosto de 2022.",
    omitUiLabel: true,
  },
  {
    id: "m08-timeline-3",
    order: 8,
    viewport: "mobile",
    label: "Linha do tempo — out. 2022",
    yStart: 0.452,
    yEnd: 0.605,
    xStart: 0.4,
    xEnd: 0.6,
    altText: "Linha do tempo: outubro de 2022.",
    omitUiLabel: true,
  },
  {
    id: "m09-timeline-4",
    order: 9,
    viewport: "mobile",
    label: "Linha do tempo — jan. 2023",
    yStart: 0.452,
    yEnd: 0.605,
    xStart: 0.6,
    xEnd: 0.8,
    altText: "Linha do tempo: janeiro de 2023.",
    omitUiLabel: true,
  },
  {
    id: "m10-timeline-5",
    order: 10,
    viewport: "mobile",
    label: "Linha do tempo — fev. 2023",
    yStart: 0.452,
    yEnd: 0.605,
    xStart: 0.8,
    xEnd: 1,
    altText: "Linha do tempo: fevereiro de 2023.",
    omitUiLabel: true,
  },
  {
    id: "m11-defesa-brendan",
    order: 11,
    viewport: "mobile",
    label: "Versão da defesa de Brendan",
    yStart: 0.605,
    yEnd: 0.875,
    xStart: 0,
    xEnd: 0.333,
    altText: "Teorias: versão da defesa de Brendan Banfield.",
    omitUiLabel: true,
  },
  {
    id: "m12-defesa-juliana",
    order: 12,
    viewport: "mobile",
    label: "Versão da defesa de Juliana",
    yStart: 0.605,
    yEnd: 0.875,
    xStart: 0.333,
    xEnd: 0.666,
    altText: "Teorias: versão da defesa de Juliana Banfield.",
    omitUiLabel: true,
  },
  {
    id: "m13-acusacao",
    order: 13,
    viewport: "mobile",
    label: "Versão da acusação",
    yStart: 0.605,
    yEnd: 0.875,
    xStart: 0.666,
    xEnd: 1,
    altText: "Teorias: versão da acusação.",
    omitUiLabel: true,
  },
  {
    id: "m14-encerramento",
    order: 14,
    viewport: "mobile",
    yStart: 0.875,
    yEnd: 1,
    altText: "Encerramento editorial do dossiê Banfield.",
    omitUiLabel: true,
  },
];

/** Desktop: blocos mais largos, sem faixas rasas; colunas empilhadas onde há grade. */
export const BANFIELD_DESKTOP_CROPS: EditorialCrop[] = [
  {
    id: "d01-capa",
    order: 1,
    viewport: "desktop",
    label: "Capa e resumo do caso",
    yStart: 0,
    yEnd: 0.12,
    altText: "Capa do dossiê Família Banfield.",
    omitUiLabel: true,
  },
  {
    id: "d02-resumo-caso",
    order: 2,
    viewport: "desktop",
    label: "Resumo do caso",
    yStart: 0.12,
    yEnd: 0.304,
    altText: "Resumo do caso com vítimas, texto e metadados.",
    omitUiLabel: true,
  },
  {
    id: "d03-mapa",
    order: 3,
    viewport: "desktop",
    label: "Mapa",
    yStart: 0.304,
    yEnd: 0.416,
    altText: "Mapa de Fairfax e região metropolitana de Washington.",
    omitUiLabel: true,
  },
  {
    id: "d03b-timeline-titulo",
    order: 4,
    viewport: "desktop",
    label: "Linha do tempo",
    yStart: 0.416,
    yEnd: 0.452,
    altText: "Título da seção linha do tempo.",
    omitUiLabel: true,
  },
  {
    id: "d04-timeline-1",
    order: 13,
    viewport: "desktop",
    label: "Linha do tempo — out. 2021",
    yStart: 0.452,
    yEnd: 0.605,
    xStart: 0,
    xEnd: 0.2,
    altText: "Linha do tempo: outubro de 2021.",
    omitUiLabel: true,
  },
  {
    id: "d05-timeline-2",
    order: 5,
    viewport: "desktop",
    label: "Linha do tempo — ago. 2022",
    yStart: 0.452,
    yEnd: 0.605,
    xStart: 0.2,
    xEnd: 0.4,
    altText: "Linha do tempo: agosto de 2022.",
    omitUiLabel: true,
  },
  {
    id: "d06-timeline-3",
    order: 6,
    viewport: "desktop",
    label: "Linha do tempo — out. 2022",
    yStart: 0.452,
    yEnd: 0.605,
    xStart: 0.4,
    xEnd: 0.6,
    altText: "Linha do tempo: outubro de 2022.",
    omitUiLabel: true,
  },
  {
    id: "d07-timeline-4",
    order: 7,
    viewport: "desktop",
    label: "Linha do tempo — jan. 2023",
    yStart: 0.452,
    yEnd: 0.605,
    xStart: 0.6,
    xEnd: 0.8,
    altText: "Linha do tempo: janeiro de 2023.",
    omitUiLabel: true,
  },
  {
    id: "d08-timeline-5",
    order: 8,
    viewport: "desktop",
    label: "Linha do tempo — fev. 2023",
    yStart: 0.452,
    yEnd: 0.605,
    xStart: 0.8,
    xEnd: 1,
    altText: "Linha do tempo: fevereiro de 2023.",
    omitUiLabel: true,
  },
  {
    id: "d09-defesa-brendan",
    order: 9,
    viewport: "desktop",
    label: "Versão da defesa de Brendan",
    yStart: 0.605,
    yEnd: 0.875,
    xStart: 0,
    xEnd: 0.333,
    altText: "Teorias: versão da defesa de Brendan Banfield.",
    omitUiLabel: true,
  },
  {
    id: "d10-defesa-juliana",
    order: 10,
    viewport: "desktop",
    label: "Versão da defesa de Juliana",
    yStart: 0.605,
    yEnd: 0.875,
    xStart: 0.333,
    xEnd: 0.666,
    altText: "Teorias: versão da defesa de Juliana Banfield.",
    omitUiLabel: true,
  },
  {
    id: "d11-acusacao",
    order: 11,
    viewport: "desktop",
    label: "Versão da acusação",
    yStart: 0.605,
    yEnd: 0.875,
    xStart: 0.666,
    xEnd: 1,
    altText: "Teorias: versão da acusação.",
    omitUiLabel: true,
  },
  {
    id: "d12-encerramento",
    order: 12,
    viewport: "desktop",
    yStart: 0.875,
    yEnd: 1,
    altText: "Encerramento editorial do dossiê Banfield.",
    omitUiLabel: true,
  },
];

export const BANFIELD_EDITORIAL_CROPS: EditorialCrop[] = [
  ...BANFIELD_MOBILE_CROPS,
  ...BANFIELD_DESKTOP_CROPS,
];

/** Cortes limpos para figuras do dossiê HTML (sem títulos de seção nem parágrafos). Fonte: v2/source-page.png @ 1620×2879. */
export type HtmlFigureCrop = {
  assetId: string;
  xStart: number;
  xEnd: number;
  yStart: number;
  yEnd: number;
  /** Pad with black to at most this width/height ratio (mobile legibility). */
  padToMaxAspect?: number;
};

export const BANFIELD_HTML_FIGURE_CROPS: HtmlFigureCrop[] = [
  {
    assetId: "fig-vitimas",
    xStart: 0.03,
    xEnd: 0.285,
    yStart: 0.218,
    yEnd: 0.33,
  },
  {
    assetId: "fig-mapa-main",
    xStart: 0.02,
    xEnd: 0.58,
    yStart: 0.405,
    yEnd: 0.5,
    padToMaxAspect: 352 / 180,
  },
  {
    assetId: "fig-mapa-inset",
    xStart: 0.55,
    xEnd: 0.985,
    yStart: 0.36,
    yEnd: 0.498,
  },
  {
    assetId: "fig-mapa",
    xStart: 0.012,
    xEnd: 0.988,
    yStart: 0.405,
    yEnd: 0.5,
  },
];

export const DOSSIER_PROCESSING_LIMITS = {
  maxPdfBytes: 25 * 1024 * 1024,
  maxPages: 20,
  renderScale: 2,
  variantWidths: [640, 960, 1440] as const,
  formats: ["webp", "avif"] as const,
  maxBlockSourceHeightPx: 1400,
};
